blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/{{GITHUB_USER}}/{{PROJECT_NAME}}/tree/main/docs
    about: Check our documentation for guides and FAQs
  - name: Discussions
    url: https://github.com/{{GITHUB_USER}}/{{PROJECT_NAME}}/discussions
    about: Ask questions and discuss ideas
